/*BEGIN_FILE_HDR
**************************************************************************
* NOTICE
* This software is the property of XiangBin Electric. Any information contained in this
* doc should not be reproduced, or used, or disclosed without the written authorization from
* XiangBin Electric.
**************************************************************************
* File Name:Common.c
********************************************************************
* Project/Product:LXT9818_PMP
* Title:
* Author:yhd
*********************************************************************
* Description:
* 1.Define common used functions
*
* (Requirements, pseudo code and etc.)
*********************************************************************
* Limitations:
*
* (limitations)
*********************************************************************
*********************************************************************
* Revision History：
*
* Version       Date         	  Author         Descriptions
* ----------    --------------  ------------   ----------------------------------------
*     1.0       2021-07-23      yhd            Original
*
*
********************************************************************
*END_FILE_HDR*/

/* Includes*/
/******************************************************************/
#include "Common.h"

/* BEGIN_FUNCTION_HDR
********************************************************************
* Function Name: Common_ExeLookUpTable
* Description:
*   This lookup table function is generated by simlink.
*
* Inputs:
* 1.u0       :x
* 2.bp0[]    :x table
* 3.table[]  :y table
* 4.maxIndex :max index of table and bp0
*
* Outputs:
* 1.y
*
* Limitations:
********************************************************************
END_FUNCTION_HDR*/
s16 Common_ExeLookUpTable(s16 u0, const s16 bp0[], const
  s16 table[], u32 maxIndex)
{
  s32 frac;
  s16 y_0;
  u32 bpIdx;

  /* Lookup 1-D
     Search method: 'linear'
     Use previous index: 'off'
     Interpolation method: 'Linear'
     Use last breakpoint for index at or above upper limit: 'on'
     Remove protection against out-of-range input in generated code: 'on'
     Rounding mode: 'simplest'
   */
  /* Prelookup - Index and Fraction
     Index Search method: 'linear'
     Use previous index: 'off'
     Use last breakpoint for index at or above upper limit: 'on'
     Remove protection against out-of-range input in generated code: 'on'
     Rounding mode: 'simplest'
   */
  /* Linear Search */
  bpIdx = maxIndex >> 1U;
  
  if(u0 < bp0[0])
  {
	  return table[0];
  }
	else/*  add else - 2021-07-28-by zyg  */
	{

	}
  
  while ((u0 < bp0[bpIdx]) && (bpIdx > 0U)) {
    bpIdx--;
  }

  while ((bpIdx < maxIndex) && (u0 >= bp0[bpIdx + 1U])) {
    bpIdx++;
  }
	/*消除polyspace警告,2021-09-27-by zyg*/
	/* polyspace-begin MISRA2012:10.8 */
  frac = (s32)(((u32)(u16)((u32)u0 - bp0[bpIdx]) << 10) /
                   (u16)(bp0[bpIdx + 1U] - bp0[bpIdx]));
	/* polyspace-end MISRA2012:10.8*/

  /* Interpolation 1-D
     Interpolation method: 'Linear'
     Use last breakpoint for index at or above upper limit: 'on'
     Rounding mode: 'simplest'
     Overflow mode: 'wrapping'
   */

  if (bpIdx == maxIndex) {
    y_0 = table[bpIdx];
  } else {
		/* polyspace-begin DEFECT:OPERATOR_PRECEDENCE  MISRA2012:10.1,10.7 */
    y_0 = (s16)((s16)(((table[bpIdx + 1U] - table[bpIdx]) * frac )>> 10) +
                    table[bpIdx]);/* polyspace-end DEFECT:OPERATOR_PRECEDENCE MISRA2012:10.1,10.7*/
  }

  return y_0;
}/*polyspace-begin  MISRA2012:6.1  MISRA2012:10.1*/
/* BEGIN_FUNCTION_HDR
********************************************************************
* Function Name:Common_CopyMem
* Description:
*   Implament copy memory function.
*
* Inputs:
* 1.des :destination address
* 2.src :source address
* 3.length:length of data to copy in byte
*
* Outputs:
*
*
* Limitations:
********************************************************************
END_FUNCTION_HDR*/
void Common_CopyMem(u8 des[],u8 src[],u8 length)
{
	u8 i;
	for(i = 0u; i < length; i++)
	{
		des[i]= src[i];
  }
}
/* BEGIN_FUNCTION_HDR
********************************************************************
* Function Name:Common_SetStatusDelay
* Description:
*   Filter a status in time domain
*
* Inputs:
* 1.status : false or true
* 2.filtertime: filtertime for status to settle
* 3.currenttime:currenttime for status, must not modified this varible
* externally.
*
* Outputs: 
* 1.filtered status
*
*
* Limitations:
********************************************************************
END_FUNCTION_HDR*/
u8 Common_SetStatusDelay(u8 status,u16 filtertime,u16 *currenttime)
{
  u8 ret = 0u;
  if(status != 0u)
  {
    if((*currenttime) < filtertime)
    {
        (*currenttime)++;

    }
    else
    {
      ret = 1u;
    }
  }
  else
  {
    (*currenttime) = 0u;
  }

  return ret;
}
